mode = "dev"
# lang: zh | en
lang = "zh"

[logger]
file = "private/logs/app.log"
# level: trace | debug | info | notice | warn | error | fatal
level = "info"
# maxAge: days
maxAge = 30
# maxSize: MB
maxSize = 128
# maxBackups: files
maxBackups = 64

[registry]
# driver: nacos | etcd
driver = "nacos"
# addrs: ["ip:port"]
addrs = ["127.0.0.1:8848"]
namespace = "public"
username = 'nacos'
password = 'nacos'
# nacos log dir
logDir = "logs"
# nacos cache dir
cacheDir = "private/data/nacos"

[httpServer]
enable = true
addr = ":8888"
usePprof = false
# recover panic
useRecovery = false
# hertz: default cors
useCORS = false
# etag
useEtag = false
# gzip level: (1~9)compression, (-1)default compression, (0)disable
useGzip = 0
# hertz: access log
useAccessLog = false
# file route
useFileRoutes = [
    # path: route path, root: file root dir
    { path = "/", root = "public" }
]

[rpcServer]
enable = true
name = "shop"
addr = ":8889"
# HttpRoute: POST {RPCServer.Name}/{ApiPath}
useHttp = true
# recover panic
useRecovery = true
# validate api input
useValidate = true
# tracing rpc
useTracing = true
# generate rpc client code
[rpcServer.useCodeGen]
enable = true
output = "hub/shop"

[rpcClient]
enable = true
timeout = 30
# discover rpc service names
discover = ["shop"]
# tracing rpc
useTracing = true

[auth]
# expire: seconds
expire = 86400
secretKey = "d6d22d29a627b3f37e8f2ddf9820d1ffbfbdeb534aaed68f2994146e939f47e9"

[db]
dsn = "root:123123@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=true&loc=Local"

[redis]
addrs = ["127.0.0.1:6379"]
db = 0
password = ""