version: '3'
# install tools
# go install github.com/go-job/job/v3/cmd/job@latest
# go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

interval: 1s

env:
  GOARCH: amd64
  CGO_ENABLED: 0

vars:
  APP_NAME: "demo"
  BUILD_DIR: "."

tasks:
  dev:
    desc: Run Dev App
    watch: true
    method: none
    sources:
      - "**/*.go"
      - "../ark/**/*.go"
      - "config.toml"
      - exclude: "hub/**/*.go"
      - exclude: "etc/query/*.go"
    deps: [ build ]
    cmds:
      - cmd: "killall -9 {{.APP_NAME}}"
        ignore_error: true
      - "./{{.APP_NAME}}"

  update:
    desc: db:migrate & gen:querier
    cmds:
      - "./{{.APP_NAME}} db:migrate"
      - "./{{.APP_NAME}} gen:querier"

  build:
    desc: Run Build App
    # deps: [ lint ]
    vars:
      BUILD_CMD: >-
        go build -ldflags="-s -w" -o {{.BUILD_DIR}}/{{.APP_NAME}}
    cmds:
      - platforms: [ darwin ]
        cmd: GOOS=darwin {{.BUILD_CMD}}
      - platforms: [ linux ]
        cmd: GOOS=linux {{.BUILD_CMD}}-linux

  lint:
    desc: Run Lint
    cmds:
      - golangci-lint run --fix