version: '3'
# go install github.com/go-task/task/v3/cmd/task@latest

interval: 1s

env:
  GOARCH: amd64
  CGO_ENABLED: 0

vars:
  APP_NAME: "demo"
  BUILD_DIR: "."

tasks:
  dev:
    desc: Run Dev App
    watch: true
    method: none
    sources:
      - "**/*.go"
      - "config.toml"
      - exclude: "app/hub/**/*.go"
      - exclude: "app/query/*.go"
    cmds:
      - cmd: "killall -9 {{.APP_NAME}}"
        ignore_error: true
      - go run .

  update:
    desc: Run App Update
    cmds:
      - go mod tidy
      - go mod download
      - go run . --update

  lint:
    desc: Run Lint
    cmds:
      - golangci-lint run --fix

  build:
    desc: Run Build App
    deps: [ lint ]
    vars:
      BUILD_CMD: >-
        go build -ldflags="-s -w" -o {{.BUILD_DIR}}/{{.APP_NAME}}
    cmds:
      - cmd: GOOS=darwin {{.BUILD_CMD}}
        platforms: [ darwin ]
      - cmd: GOOS=linux {{.BUILD_CMD}}-linux
        platforms: [ linux ]

  install:tools:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest