// Code generated by ark. DO NOT EDIT.

package shop

import (
	"context"

	"github.com/arklib/ark"
)

type ApiShopItemGetIn struct {
	Id int `frugal:"1,default" json:"id" vd:"required"`
}

type ApiShopItemGetOut struct {
	Id          int    `frugal:"1,default" json:"id"`
	Title       string `frugal:"2,default" json:"title"`
	Description string `frugal:"3,default" json:"description"`
}

type Service struct {
	srv *ark.Server
}

func New(srv *ark.Server) *Service {
	return &Service{srv}
}

func (s *Service) ApiShopItemGet(ctx context.Context, in *ApiShopItemGetIn) (out *ApiShopItemGetOut, err error) {
	out = new(ApiShopItemGetOut)
	err = s.srv.RPC(ctx, "shop/item/get", in, out)
	return
}
